# This workflow will install Python dependencies, run tests with a single version of Python

name: Tests

on:
  push:
    branches:
    - '!master'
    - '*'
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.6]
        uv-version: [0.6.11]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.6"
    - name: Install uv ${{ matrix.uv-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install uv==${{ matrix.uv-version }}
        
    - name: View uv --help
      run: uv --help
    - name: Install dependencies
      shell: bash
      run: uv sync

    - name: Test with pytest
      run: |
        python -m uv run python -m pytest -v tests
